using System.Collections;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.Rendering;

public class InputController : MonoBehaviour
{
    [Header("Scriptable Object Reference")]
    [SerializeField] private VoidEventChannel fov_EventChannel;
    [SerializeField] private InputEventChannel input_EventChannel;
    [SerializeField] private AudioPitcherSO dashAudio;
    [SerializeField] private VoidEventChannel disableGrapple_EventChannel;
    [SerializeField] private FloatEventChannel iFrame_EventChannel;
    [SerializeField] private FloatEventChannel playerDashReset_EventChannel;

    [Header("Camera Settings")]
    [SerializeField] private float sensitivity = 15f;

    [SerializeField] private float minSensitivity = 1f;

    [SerializeField] private float maxSensitivity = 30f;
    public float Sensitivity 
    { 
        get { return sensitivity; } 
        set { sensitivity = Mathf.Clamp(value, minSensitivity, maxSensitivity); } 
    }

    [Header("Basic Movement Settings")]
    [Tooltip("The speed the player moves at")]
    [SerializeField] private float walkSpeed = 60f;

    [Tooltip("Adds more drag to the players velocity")]
    [SerializeField] private float dragRate = 5f;

    [Tooltip("How high the player can jump")]
    [SerializeField] private float jumpForce = 50f;

    [Header("Air Control Settings")]
    [Tooltip("The amount of air resistance the player experiences")]
    [SerializeField] private float airDragRate = 3f;

    [Tooltip("The players movement speed when airborn")]
    [SerializeField] private float airSpeed = 30f;

    [Header("Dash Settings")]
    [SerializeField] private float dashCooldown = 1f;

    [SerializeField] private float dashForce = 50f;

    [SerializeField] private FloatEvent iFrameDuration;

    private bool canDash = true;

    //Slide References
    [Header("Slide Settings")]
    [SerializeField] GameObject parryBox;

    [Tooltip("How long the player is able to slide for")]
    [SerializeField] float maxSlideTime = 5f;

    [Tooltip("How fast the player can slide")]
    [SerializeField] float slideSpeed = 5f;

    [SerializeField] private float slideScaleY = 0.5f;

    [SerializeField] private float transitionTime = 0.3f;

    float slideTimer;
    Vector3 slideStartCameraPos;
    bool isSliding;
    float slopeAngle;
    Transform cameraHolder;

    //DashVariables
    float dashStartingTimer;
    float dashTimer = 2;
    float maxDashForce = 50;
    float minDashForce = 5;
    float minDashTimer;

    [Header("Parry Settings")]
    [Tooltip("The number of frames the parry box is active on the start of a slide")]
    [SerializeField] private int parryFrameCount;

    float actionDuration => (1f / 60f) * parryFrameCount;

    [Header("Floating Rigidbody Settings")]
    [Tooltip("The maximum angle the player can walk up without losing speed")]
    [SerializeField] private float maxSlopeAngle = 45f;

    [Tooltip("The height the floating rigidbody is offset from the ground")]
    [SerializeField] private float heightOffset = 1f;

    [Tooltip("How long the raycast detecting the ground is")]
    [SerializeField] private float offsetRayDistance = 1f;

    [Tooltip("Adds force to the total Y-offset")]
    [SerializeField] private float offsetStrength = 200f;

    [Tooltip("Affects how controlled the offset is")]
    [SerializeField] private float offsetDamper = 10f;

    [Tooltip("The layers the player can walk on")]
    [SerializeField] private LayerMask groundLayer;

    //Input References
    private PlayerControls playerControls;
    private PlayerControls.MovementActions movementActions;
    private PlayerControls.CameraActions cameraActions;

    private InputEvent inputEvent;

    //Physics References
    private Rigidbody rb;

    private RaycastHit groundHit;

    //Camera References
    private Camera cam;

    private float lookRotation;

    private Vector2 moveInput;

    private PlayerInteractor playerInteractor;

    private AudioSource source;

    //Getters
    private bool isGrounded;
    private bool isMoving;
    private bool applyMovementEffects;
    public bool IsGrounded { get { return isGrounded; } }
    public bool IsMoving { get { return isMoving; } }
    public bool ApplyMovementEffects { get { return applyMovementEffects; } }
    public Vector2 MoveInput { get { return moveInput; } }

    //Constants
    private const float EFFECT_THRESHOLD = 60f;
    private const float LOOK_CLAMP = 90f;
    private const float SENSITIVITY_SCALE_FACTOR = 100f;

    void Awake()
    {
        //Initialize Controls
        playerControls = new PlayerControls();
        movementActions = playerControls.Movement;
        cameraActions = playerControls.Camera;

        //Initialize inputs on other scripts
        inputEvent = new InputEvent(playerControls);

        rb = GetComponent<Rigidbody>();

        cam = GetComponentInChildren<Camera>();

        playerInteractor = GetComponentInChildren<PlayerInteractor>();

        source = GetComponent<AudioSource>();

        input_EventChannel.CallEvent(inputEvent);

        cameraHolder = cam.transform.parent;

        //Cache starting camera position
        slideStartCameraPos = cameraHolder.localPosition;
    }

    private void Start()
    {
        playerDashReset_EventChannel.CallEvent(new(dashTimer));
    }

    void Update()
    {
        //Ground raycast
        isGrounded = Physics.Raycast(transform.position, -Vector3.up, out groundHit, offsetRayDistance, groundLayer);
    }

    /// <summary>
    /// Enables/Disables input actions
    /// </summary>
    /// <param name="canMove"></param>
    /// <param name="canLook"></param>
    public void SetInputActions(bool canMove, bool canLook)
    {
        if (canMove)
            movementActions.Enable();
        else
            movementActions.Disable();

        if (canLook)
            cameraActions.Enable();
        else
            cameraActions.Disable();
    }

    //Movement
    void FixedUpdate()
    {
        Move();
        AirControl();
        Sliding();
    }
    private Vector3 MoveDirection()
    {
        //Read player input
        moveInput = movementActions.Move?.ReadValue<Vector2>() ?? Vector2.zero;

        //Project two vectors onto an orthagonal plane and multiply them by the players x and y inputs
        Vector3 moveDirection =
            (Vector3.ProjectOnPlane(transform.forward, Vector3.up) * moveInput.y +
            Vector3.ProjectOnPlane(transform.right, Vector3.up) * moveInput.x);
        //Normalize the two projected inputs added together to get the movement direction
        moveDirection.Normalize();

        //Returns unit vector
        return moveDirection;
    }
    private void Move()
    {
        if (!isGrounded) return;

        //Check if moving
        isMoving = movementActions.Move.inProgress;

        //Apply walk speed to the movement vector
        Vector3 moveForce = MoveDirection() * walkSpeed;

        //Find the angle between the players up position and the groundHit
        slopeAngle = Vector3.Angle(Vector3.up, groundHit.normal);

        //Set to (0, 0, 0)
        Vector3 yOffsetForce = Vector3.zero;

        //If surface angle is within max angle
        if (slopeAngle <= maxSlopeAngle)
        {
            //Find difference between ground distance and the offset
            float yOffsetError = (heightOffset - groundHit.distance);

            //Find the dot product of vector3.up and of the players velocity
            float yOffsetVelocity = Vector3.Dot(Vector3.up, rb.velocity);

            //Set the offset force of the floating rigidbody
            yOffsetForce = Vector3.up * (yOffsetError * offsetStrength - yOffsetVelocity * offsetDamper);
        }
        //Calculate the combinded force between direction and offset
        Vector3 combinedForces = moveForce + yOffsetForce;

        //Calculate damping forces by multiplying the drag and player velocity
        Vector3 dampingForces = rb.velocity * dragRate;

        //Add forces to rigidbody
        rb.AddForce((combinedForces - dampingForces) * (100 * Time.fixedDeltaTime));
    }

    private bool OnSlope()
    {
        return slopeAngle < maxSlopeAngle && slopeAngle != 0;
    }

    private Vector3 SlopeMoveDirection()
    {
        return Vector3.ProjectOnPlane(MoveDirection(), groundHit.normal).normalized;
    }

    private void AirControl()
    {
        if (isGrounded) return;

        Vector3 moveForce = airSpeed * MoveDirection();

        Vector3 dampingForces = rb.velocity * airDragRate;

        Vector3 totalForce = new(moveForce.x - dampingForces.x, moveForce.y, moveForce.z - dampingForces.z);

        rb.AddForce((100 * Time.fixedDeltaTime) * totalForce);
    }

    //Camera movement
    void LateUpdate() => Look();
    private void Look()
    {
        //Check if player is looking too far up or down
        applyMovementEffects = lookRotation > EFFECT_THRESHOLD || lookRotation < -EFFECT_THRESHOLD;

        //Read mouse input
        //If implementing pausing, change this
        Vector2 lookForce = cameraActions.Look?.ReadValue<Vector2>() ?? Vector2.zero;

        //Turn the player with the X-input
        gameObject.transform.Rotate(lookForce.x * (sensitivity * Vector3.up) / SENSITIVITY_SCALE_FACTOR);

        //Add Y-input multiplied by sensitivity to float
        lookRotation += (-lookForce.y * sensitivity / SENSITIVITY_SCALE_FACTOR);

        //Clamp the look rotation so the player can't flip the camera
        lookRotation = Mathf.Clamp(lookRotation, -LOOK_CLAMP, LOOK_CLAMP);

        //Set cameras rotation
        cam.transform.eulerAngles = new(lookRotation, cam.transform.eulerAngles.y, 0);
    }

    private void New_Dash(InputAction.CallbackContext ctx)
    {
        if (!canDash) return;

        //If player isn't moving
        if (MoveDirection() == Vector3.zero) return;

        canDash = false;

        //Enable IFrames
        iFrame_EventChannel.CallEvent(iFrameDuration);

        //Ungrapple
        disableGrapple_EventChannel.CallEvent(new());

        rb.AddForce(MoveDirection() * dashForce, ForceMode.Impulse);

        dashAudio.Play(source);

        fov_EventChannel.CallEvent(new());

        Invoke(nameof(ResetDash), dashCooldown);
    }
    private void ResetDash() => canDash = true;


    private void Dash(InputAction.CallbackContext ctx)
    {
        if(!canDash)
        {
            return;
        }

        //If player isn't moving
        if (MoveDirection() == Vector3.zero) return;

        float normalizedTimer = ((Time.time - dashStartingTimer)) / dashTimer;

        if(normalizedTimer < .3f)
        {
            return;
        }

        canDash = false;

        //Enable IFrames
        //iFrame_EventChannel.CallEvent(iFrameDuration);

        float totalDashForce = Mathf.Lerp(minDashForce, maxDashForce, normalizedTimer);

        Debug.Log(totalDashForce);

        rb.AddForce(MoveDirection() * totalDashForce, ForceMode.Impulse);

        dashAudio.Play(source);

        fov_EventChannel.CallEvent(new());

        //Start Dash Timer
        dashStartingTimer = Time.time;

        //CallEvent Channel To Reset Dash UI
        playerDashReset_EventChannel.CallEvent(new(dashTimer));
        canDash = true;
    }

    private void Jump(InputAction.CallbackContext ctx)
    {
        if (!IsGrounded) return;

        Vector3 currentDirection = MoveDirection();

        rb.AddForce(new(currentDirection.x, jumpForce, currentDirection.z), ForceMode.Impulse);
    }

    #region Slide Functions
    private void StartSlide(InputAction.CallbackContext ctx)
    {
        if (MoveDirection() == Vector3.zero || !IsGrounded) return;

        //Increase FOV
        fov_EventChannel.CallEvent(new());        

        //Shrink player height
        StartCoroutine(LerpCamera(new Vector3(cameraHolder.localPosition.x, cameraHolder.localPosition.y - slideScaleY, cameraHolder.localPosition.z), transitionTime)); ;

        //Reset slide timer
        slideTimer = 0;

        isSliding = true;
    }

    private void Sliding()
    {
        if (!isSliding) return;

        if (!OnSlope() || rb.velocity.y > -0.1f)
        {
            slideTimer += Time.deltaTime;

            rb.AddForce(MoveDirection() * slideSpeed, ForceMode.Force);
        }
        else
        {
            rb.AddForce(SlopeMoveDirection() * slideSpeed, ForceMode.Force);
        }

        if (slideTimer > maxSlideTime)
            ResetSlide();
    }

    private void EndSlide(InputAction.CallbackContext ctx)
    {
        ResetSlide();
    }

    private void ResetSlide()
    {
        StopAllCoroutines();
        parryBox.SetActive(false);

        //Reset height
        StartCoroutine(LerpCamera(slideStartCameraPos, transitionTime));

        isSliding = false;
    }

    IEnumerator LerpCamera(Vector3 endPos, float duration)
    {
        float elapsed = 0;
        Vector3 startPos = cameraHolder.localPosition;

        while (elapsed < duration)
        {
            elapsed += Time.deltaTime;

            cameraHolder.localPosition = Vector3.Lerp(startPos, endPos, elapsed / duration);

            yield return null;
        }

        cameraHolder.localPosition = endPos;
    }

    //Activate the parrybox for the specified number of frames
    IEnumerator ActiveParry()
    {
        parryBox.SetActive(true);
        yield return new WaitForSeconds(actionDuration);
        Debug.Log(actionDuration);
        parryBox.SetActive(false);
    }

    #endregion

    private void StartInteract(InputAction.CallbackContext ctx) => playerInteractor.CanInteract(true);
    private void EndInteract(InputAction.CallbackContext ctx) => playerInteractor.CanInteract(false);

    private void OnEnable()
    {
        movementActions.Enable();

        cameraActions.Enable();

        movementActions.Dash.performed += Dash;

        movementActions.Jump.performed += Jump;

        movementActions.Interact.performed += StartInteract;

        movementActions.Interact.canceled += EndInteract;

        movementActions.Slide.performed += StartSlide;

        movementActions.Slide.canceled += EndSlide;
    }
    private void OnDisable()
    {
        movementActions.Disable();

        cameraActions.Disable();

        movementActions.Dash.performed -= Dash;

        movementActions.Jump.performed -= Jump;

        movementActions.Interact.performed -= StartInteract;

        movementActions.Interact.canceled -= EndInteract;

        movementActions.Slide.performed -= StartSlide;

        movementActions.Slide.canceled -= EndSlide;

        playerControls.Fishing.Disable();

        playerControls.Combat.Disable();
    }

    public void SwitchInputMode(BoolEvent isInCombat)
    {
        input_EventChannel.SwitchControlModes(inputEvent, isInCombat.Value);
    }
}
